// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    FeedingRow: typeof import('./src/components/FeedingRow.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MdiCoffee: typeof import('virtual:vite-icons/mdi/coffee')['default']
    MdiFlower: typeof import('virtual:vite-icons/mdi/flower')['default']
    NextFeedings: typeof import('./src/components/NextFeedings.vue')['default']
    Pill: typeof import('./src/components/Pill.vue')['default']
    PlanterCard: typeof import('./src/components/PlanterCard.vue')['default']
    PlanterCardFeeding: typeof import('./src/components/PlanterCardFeeding.vue')['default']
    PlanterCardFeedings: typeof import('./src/components/PlanterCardFeedings.vue')['default']
    Planters: typeof import('./src/components/Planters.vue')['default']
    PlanterTimeline: typeof import('./src/components/PlanterTimeline.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Table: typeof import('./src/components/Table.vue')['default']
  }
}

export { }
